# Generated by Django 3.1.7 on 2021-06-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pento_app', '0002_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
